import Head from "next/head";
import Image from "next/legacy/image";
import axios from "axios";
import { useState, useEffect } from "react";
import { BsSearch } from "react-icons/bs";
import Weather from "../components/Weather";
import WeatherOneCall from "../components/WeatherOneCall";
import Loader from "../components/Loader";
import Debug from "../components/Debug";

export default function Home() {
  // const [city, setCity] = useState("");
  const [cityState, setCityState] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
  const [lat, setLat] = useState("");
  const [long, setLong] = useState("");
  const [updatedOneCallURL, setUpdatedOneCallURL] = useState("");

  // var country_code = "US";

  // const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}&units=imperial`;

  const geoUrl = `http://api.openweathermap.org/geo/1.0/direct?q=${cityState},US&limit=5&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  let oneCallURL = `https://api.openweathermap.org/data/3.0/onecall?lat=${lat}&lon=${long}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchLocation = async () => {
    const response = await axios.get(geoUrl);
    console.log(response.data);
    setLat(response.data[0].lat);
    setLong(response.data[0].lon);
    setUpdatedOneCallURL(
      `https://api.openweathermap.org/data/3.0/onecall?lat=${response.data[0].lat}&lon=${response.data[0].lon}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`
    );
    console.log("LOCATION RECEIVED.");
  };

  const fetchWeather = async () => {
    console.log("FETCHING WEATHER.");
    const res = await axios.get(
      `https://api.openweathermap.org/data/3.0/onecall?lat=34.2257282&lon=-77.9447107&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`
    );
    setWeather(res.data);
    console.log("after setWeather().");
    console.log(weather);
  };

  const fetchData = async (e) => {
    e.preventDefault();
    setLoading(true);
    await fetchLocation();
    await fetchWeather();
    setLoading(false);
  };

  useEffect(() => {
    window.addEventListener("keyup", (e) => {
      if (e.key === "Enter") {
        e.target.blur();
      }
    });
  }, []);

  return (
    <div className="relative h-screen">
      <Head>
        <title>Weather - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cloud.png" />
      </Head>

      <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]" />
      <Image
        src="https://images.unsplash.com/photo-1562155618-e1a8bc2eb04f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1791&q=80"
        className="object-cover"
        layout="fill"
        alt="#"
      />

      {/* SEARCH */}
      <div className="relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10">
        <form
          className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl"
          onSubmit={fetchData}
        >
          <div>
            <input
              className="bg-transparent backdrop-blur-sm text-white border-none focus:outline-none text-2xl placeholder:text-gray"
              type="text"
              placeholder="Search City"
              onChange={(e) => setCityState(e.target.value)}
            />
            <p className="mt-2 text-sm text-gray-500">
              U.S. Locations <span>ONLY</span>. Ex: Wilmington, NC
            </p>
          </div>
          <button>
            <BsSearch className="text-white/80" size={20} />
          </button>
        </form>
      </div>

      {/* DEBUG */}
      <Debug
        debugData={[
          cityState,
          geoUrl,
          lat,
          long,
          updatedOneCallURL,
          oneCallURL,
        ]}
      />

      {/* WEATHER DISPLAY */}

      {loading ? (
        <Loader className="text-center" />
      ) : (
        weather.main && <WeatherOneCall data={weather} />
      )}

      {/* {weather.main ? <Weather data={weather} /> : <Loader />} */}
    </div>
  );
}
